// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuyPzsoxypo8MkY2TPgJjhCl2o5QR3mOo',
    appId: '1:923867099296:android:9c4d641e7c7f538a27d9c5',
    messagingSenderId: '923867099296',
    projectId: 'web-test-b8d96',
    databaseURL: 'https://web-test-b8d96-default-rtdb.firebaseio.com',
    storageBucket: 'web-test-b8d96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmI9E7t-FvWTYZ66kR9QlvCEF7HarHpGE',
    appId: '1:923867099296:ios:2a330965584f77c127d9c5',
    messagingSenderId: '923867099296',
    projectId: 'web-test-b8d96',
    databaseURL: 'https://web-test-b8d96-default-rtdb.firebaseio.com',
    storageBucket: 'web-test-b8d96.firebasestorage.app',
    iosClientId: '923867099296-s6gqfb49qktd9jfmm4tmhu8mok8qkphv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvBuilder',
  );
}
